version: "3"
services:

  pgadmin:
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    logging:
      driver: none
    volumes:
      - "/data/pgadmin:/root/.pgadmin"

  postgres:
    container_name: WorkForceDB
    environment:
      POSTGRES_DB: work_force_db
      POSTGRES_PASSWORD: "admin#123"
      POSTGRES_USER: admin
    image: "postgres:9.5"
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

#  redis:
#    image: "redis:alpine"

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"

  django:
    #build: ./
    image: samuira/python_img:tution_mastor
    command: "daphne -b 0.0.0.0 -p 8000 WorkForce.asgi:application"
    # command: "python manage.py runserver 0.0.0.0:8000"
    #container_name: WorkForce
    entrypoint: /backend/entrypoint.sh
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ".:/backend"

  client:
    # build:
    #   context: ./angular-tution-mastor/
    #   dockerfile: ./Dockerfile
    image: samuira/angular_img:tution_mastor
    entrypoint: ./entrypoint.sh
    command: ["ng", "serve","--host", "0.0.0.0"]
    ports:
      - "4200:4200"
    volumes:
      - "./angular-tution-mastor:/usr/src/app"

  nginx:
    # build:
    #   context: ./nginx/
    #   dockerfile: ./Dockerfile
    image: samuira/nginx_img:tution_mastor
    restart: always
    ports:
      - "8089:80"
    volumes:
      - "./angular-tution-mastor/dist:/usr/src/app/dist"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ".:/backend"
    depends_on:
      - django
      - client

  celery:
    #build: ./
    image: samuira/python_img:tution_mastor
    command: celery -A WorkForce worker -l info
    volumes:
      - .:/backend
    depends_on:
      - postgres
      #- redis
      - rabbit
      - django

  celery-beat:
    #build: ./
    image: samuira/python_img:tution_mastor
    command: celery -A WorkForce beat --pidfile= -l info
    volumes:
      - .:/backend
    depends_on:
      - postgres
      #- redis
      - rabbit
      - django

volumes:
  pgdata: ~
